name: phase3-tgw-Hub Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "environments/hub/**"
      - "modules/**"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-hub
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest

    environment: production

    defaults:
      run:
        working-directory: environments/hub

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-terraform-role-v1
          aws-region: ap-south-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
