name: Phase 3 - Hub Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/phase3-hub/**"
      - "terraform/modules/**"
      - ".github/workflows/phase3-hub.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  phase3-hub:
    name: Phase 3 - Hub
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/phase3-hub

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------------
      # AWS OIDC
      # ------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::878962827886:role/Rajesh-devops
          aws-region: ap-south-1

      # ------------------------------------------------
      # Verify AWS
      # ------------------------------------------------
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity
          aws ec2 describe-vpcs --region ap-south-1

      # ------------------------------------------------
      # Check Terraform State Bucket
      # ------------------------------------------------
      - name: Check Terraform State Bucket
        run: |
          aws s3api head-bucket \
            --bucket rajesh-terraform-state-878962827886

          aws s3 ls \
            s3://rajesh-terraform-state-878962827886

      # ------------------------------------------------
      # Check Required Variables
      # ------------------------------------------------
      - name: Check Required Variables
        env:
          TRANSIT_GATEWAY_ID: ${{ vars.TRANSIT_GATEWAY_ID }}
          SPOKE_ACCOUNT_ID: ${{ vars.SPOKE_ACCOUNT_ID }}
        run: |
          if [ -z "$TRANSIT_GATEWAY_ID" ]; then
            echo "ERROR: TRANSIT_GATEWAY_ID GitHub variable is missing"
            exit 1
          fi

          if [ -z "$SPOKE_ACCOUNT_ID" ]; then
            echo "ERROR: SPOKE_ACCOUNT_ID GitHub variable is missing"
            exit 1
          fi

          echo "Required variables are configured."

      # ------------------------------------------------
      # Terraform
      # ------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
          TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
        run: |
          terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        env:
          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
          TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
        run: |
          terraform apply -auto-approve tfplan   