name: Phase 3 - Spoke Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/phase3-spoke/**"
      - "terraform/modules/**"
      - ".github/workflows/phase3-spoke.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  phase3-spoke:
    name: Phase 3 - Spoke TGW Attachment
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/phase3-spoke

    steps:

      # ------------------------------------------------
      # 1. Checkout
      # ------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------------
      # 2. AWS authentication - SPOKE ACCOUNT
      # ------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434097521299:role/testingdummy
          aws-region: ${{ env.AWS_REGION }}

      # ------------------------------------------------
      # 3. Verify AWS account
      # ------------------------------------------------
      - name: Check AWS Identity
        run: |
          aws sts get-caller-identity

      # ------------------------------------------------
      # 4. Get TGW ID from GitHub Variable
      # ------------------------------------------------
      - name: Check Transit Gateway ID
        run: |
          if [ -z "${{ vars.TRANSIT_GATEWAY_ID }}" ]; then
            echo "ERROR: TRANSIT_GATEWAY_ID is not configured"
            echo "Go to:"
            echo "Settings -> Secrets and variables -> Actions -> Variables"
            echo "Create TRANSIT_GATEWAY_ID"
            exit 1
          fi

          echo "TRANSIT_GATEWAY_ID is configured."

      # ------------------------------------------------
      # 5. Setup Terraform
      # ------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      # ------------------------------------------------
      # 6. Terraform Init
      # ------------------------------------------------
      - name: Terraform Init
        run: |
          terraform init -input=false



          - name: Check TGW ID
            run: |
               if [ -z "${{ vars.TRANSIT_GATEWAY_ID }}" ]; then
                echo "ERROR: TRANSIT_GATEWAY_ID is not configured"
                exit 1
                 fi  

      # ------------------------------------------------
      # 7. Terraform Validate
      # ------------------------------------------------
      - name: Terraform Validate
        run: |
          terraform validate

      # ------------------------------------------------
      # 8. Terraform Plan
      # ------------------------------------------------
      - name: Terraform Plan
        env:
          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
        run: |
          terraform plan \
            -input=false \
            -out=tfplan

      # ------------------------------------------------
      # 9. Terraform Apply
      # ------------------------------------------------
      - name: Terraform Apply
        env:
          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            tfplan     