name: Phase 3 - Spoke Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/phase3-spoke/**"
      - "terraform/modules/**"
      - ".github/workflows/phase3-spoke.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  phase3-spoke:
    name: Phase 3 - Spoke Attachment
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/phase3-spoke

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434097521299:role/testingdummy
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve        

