name: Phase 3 - Hub Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/phase3-hub/**"
      - "terraform/modules/**"
      - ".github/workflows/phase3-hub.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  phase3-hub:
    name: Phase 3 - Hub
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/phase3-hub

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-test-role  
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      # Get TGW ID automatically from Hub
      - name : 
        id: tgw
        run: |
          TGW_ID=$(aws ec2 describe-transit-gateways \
            --region ap-south-1 \
            --query 'TransitGateways[?State==`available`].TransitGatewayId | [0]' \
            --output text)

          if [ -z "$TGW_ID" ] || [ "$TGW_ID" = "None" ]; then
            echo "ERROR: No available Transit Gateway found in Hub account"
            exit 1
          fi

          echo "Transit Gateway found"

          
      - name: Check Terraform State Bucket
        run: |
          aws s3api head-bucket \
            --bucket rajesh-terraform-state-878962827886

          aws s3 ls \
            s3://rajesh-terraform-state-878962827886

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: |
          terraform init -reconfigure -input=false

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_transit_gateway_id: ${{ steps.tgw.outputs.transit_gateway_id }}
          TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
        run: |
          terraform plan \
            -input=false \
            -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_transit_gateway_id: ${{ steps.tgw.outputs.transit_gateway_id }}
          TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            tfplan     