name: Phase 3 - Hub

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "terraform/modules/**"
      - "terraform/phase3/hub/**"
      - ".github/workflows/phase3-hub.yaml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform/phase3/hub

jobs:

  terraform:
    name: Deploy Phase 3 Hub
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-test-role 
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt 

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve    